### ISSUE TITLE
exclude some tasks

### ISSUE THREAD

**Issue by pastorjack** [702573N/Obsidian-Tasks-Calendar#26]
I know this is more of a dataview question, but I can't figure it out. 

I have a section in my daily notes under a h1 "Log" underneath are checkboxes that I use for habit tracking. I would like to exclude them from the calendar so it isn't cluttered. So I want all tasks displayed, except the ones under the heading "Log." It seems like I should be able to do this with dv.pages as in your example:
```dataviewjs
await dv.view("Resources/Scripts/taskscal", {pages: "dv.pages().file.tasks.where(t => t.tags.includes('#Pierre'))", view: "month", firstDayOfWeek: 1, options: "style3"})
```
I think it would be something like this
```dataviewjs
await dv.view("Resources/Scripts/taskscal", {pages: "dv.pages().file.tasks.where(p=>p.checked).where(p => String(p.section).includes("Log"))", view: "month", firstDayOfWeek: 1, options: "style3"})
```
I'd really appreciate any help!

**Comment by 702573N** [comment]
Hi @pastorjack,
take a look:

```
await dv.view("Resources/Scripts/taskscal", {pages: "dv.pages().file.tasks.where(t=>!t.checked && t.header.subpath != 'Log')", view: "month", firstDayOfWeek: 1, options: "style3"})
```

If you would like to see the checked tasks instead of the unchecked, then remove the leading `!` on 
`!t.checked`.

To read the section string and looking for including words is a possible way, but there is a better way by reading the subpath from the header or the section key (both are the same in dataview). With the command `!=` we focus the `not equal` data.

**Comment by pastorjack** [comment]
That is perfect! Thank you so much!!!
