### ISSUE TITLE
Support showing task icons when hiding file names

### ISSUE THREAD

**Issue by wenlzhang** [702573N/Obsidian-Tasks-Calendar#30]
In the master branch of the code, task icons would disappear if file names are hidden.

**Comment by 702573N** [comment]
Please check if you have completely closed Obsidian und restart after the update! And check that no option like noIcons is active!

**Comment by wenlzhang** [comment]
After restarting Obsidian, task icons would show up as expected with Obsidian Desktop. However, it still does not work with Obsidian iOS.

**Comment by 702573N** [comment]
On all my iOS devices (iPhone, iPad) the task icons are visible on hiding the filenames. Please check you have completely closed the obsidian app even in the background of your iOS device and restart the app.

Feel free to post your dv.view() command so I can use this to check your calendar view settings.

Another question: Could it be that you mean the note icons instead of the task icons?

**Comment by 702573N** [comment]
It seems there is a conflict with the lineClamp. If you choose noLineClamp inside options, all looks good. I'm working on a fix.
