### ISSUE TITLE
dataview error when pasting default dvjs code

### ISSUE THREAD

**Issue by bayradberry** [702573N/Obsidian-Tasks-Calendar#33]
dataview installed = yes
dvjs turned on in dataview settings = yes
folder created = yes
files uploaded to folder = yes
default sample dvjs pasted into new note = yes

error on render:

`
Evaluation Error: SyntaxError: Unexpected token '<'
    at new Function (<anonymous>)
    at DataviewInlineApi.view (plugin:dataview:19624:28)
    at async eval (eval at <anonymous> (plugin:dataview), <anonymous>:1:54)
    at async DataviewJSRenderer.render (plugin:dataview:19705:13)
    `

can you pleas let me know if i'm missing something? thanks!

**Comment by 702573N** [comment]
Hi, thanks for trying it out. I'm sure we can work it out together. According to your error message, there is a "<" somewhere in your dataviewjs code block. This makes me wonder what you wrote in your code block, because in my example this character does not appear anywhere. Please send me a screenshot of your code line (please do not copy the text on purpose).

**Comment by bayradberry** [comment]
yeah, i goofed. i tried to save the link from git and it saved as an html file. :/ 

i pasted the code in and replaced the files, all is good now. safe to close. thanks!

**Comment by 702573N** [comment]
I'm glad to hear that. Have fun with it.
