### ISSUE TITLE
Using startPosition with calendar week displays wrong week

### ISSUE THREAD

**Issue by bifidotftw** [702573N/Obsidian-Tasks-Calendar#39]
```dataviewjs
  await dv.view("tasksCalendar", {pages: "", view: "week", firstDayOfWeek: 1, options: "style8 noDailyNote filter",
  startPosition: "2022-W49"})
  ```

The subsequent week is displayed instead of the one specified in 'startPosition'.
In the example week 50 instead of 49 is selected.

Thank you for the great plugin!

**Comment by 702573N** [comment]
You are using the wrong format to declare the week. Unfortunately it is not possible at the moment to select a custom week by week number. You have to set any day by date (YYYY-MM-DD) from within your favourite week.

https://github.com/702573N/Obsidian-Tasks-Calendar#startposition
________________________________
Von: bifidotftw ***@***.***>
Gesendet: Monday, December 19, 2022 11:34:35 AM
An: 702573N/Obsidian-Tasks-Calendar ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [702573N/Obsidian-Tasks-Calendar] Using startPosition with calendar week displays wrong week (Issue #39)


await dv.view("tasksCalendar", {pages: "", view: "week", firstDayOfWeek: 1, options: "style8 noDailyNote filter", startPosition: "2022-W49"})


The subsequent week is displayed instead of the one specified in 'startPosition'.
In the example week 50 instead of 49 is selected.

Thank you for the great plugin!

**Comment by 702573N** [comment]
Please take a look at the current release: https://github.com/702573N/Obsidian-Tasks-Calendar/releases/tag/1.3.5

**Comment by bifidotftw** [comment]
Thank you very much for the quick fix.
The format I used is the default in the [Periodic Notes](https://github.com/liamcain/obsidian-periodic-notes) plugin.

Personally I like the format gggg-Www (e.g. 2022-W49) and since it is the standard it might be useful to support it as well.
In any case in the plugin settings of Periodic Notes the format can be easily changed (see below).
![image](https://user-images.githubusercontent.com/23495255/209543609-0f3f1075-b672-46d1-b3ff-121d2fb993f4.png)

Thank you very much for the quick fix!
