### ISSUE TITLE
Custom CSS resulting in error

### ISSUE THREAD

**Issue by elvarb** [702573N/Obsidian-Tasks-Calendar#44]
Using the css example from the main readme 

css: ".tasksCalendar.style4[view='week'] .grid { height: 300px !important }"

Just results in the following error

Cannot access 'rootNode' before initialization

Is this a bug or am I just using it wrong?

**Comment by 702573N** [comment]
The css parameter is broken since the latest main release. It will be fixed shortly.

Am 27.12.2022 um 14:20 schrieb elvarb ***@***.***>:

﻿

Using the css example from the main readme

css: ".tasksCalendar.style4[view='week'] .grid { height: 300px !important }"

Just results in the following error

Cannot access 'rootNode' before initialization

Is this a bug or am I just using it wrong?
