### ISSUE TITLE
I made a simple wrapper plugin for your two amazing views.

### ISSUE THREAD

**Issue by Leonezz** [702573N/Obsidian-Tasks-Calendar#57]
Hi, 

Sorry to bother, I am a developer and also a researcher who loves using Obsidian to take notes. And I find both of your two view scripts (if I may call them that way) are great for obsidian-based task management. But I am worried about if I just download the scripts and use them locally, I can't get the latest update.

I happen to know a little bit javescript/typescript, thus I made a simple wrapper plugin (https://github.com/Leonezz/obsidian-tasks-calendar-wrapper) today and it took me around half a day. I implemented a simple setting page for the two views and the core functionality still relies on your scripts.

I was wondering how do you like about this plugin and if you are interested to participate to maintain it. Please let me know if you are interested, I can really use your help.

All the best,
zhuwenq

**Comment by 702573N** [comment]
Thank you for your message and this brilliant idea. I needed a more suitable representation of my tasks (calendar/timeline) for my job, which is why I started tinkering with the simplest possible means (Dataview Plugin) on the fly. This cobbled-together something then became more and more complex and bigger, which is why I made it available to people on GitHub at some point. My concern was and is to see this functionality integrated into the Task Plugin at some point, so that I don't have to take care of it myself. I had also spoken to @claremacrae about this some time ago. Unfortunately, it turns out that integration is not that easy. At the moment, I'm actually glad for every minute of time I don't have to invest in these scripts. On some days I would even like to pull the plug on GitHub, because there are constantly requests, change requests and bugs being transmitted and everyone wants to see their individual wishes realised. For a programmer, this is certainly all child's play, but I never learned programming and accordingly work in a completely different field. I would be happy if they would continue to maintain the wrapper themselves. Please excuse my escape from this additional responsibility.

**Comment by Leonezz** [comment]
Totally understandable, I am now wrappering you scripts and call `dv.executeJs` in the plugin, I was thinking to rewrite your scripts so that they can be integrated completely to the plugin, and maybe we can archieve it together. But your decision is totally understandable, we all should focus on things that are more attracted to ourselves. I wish you good luck and hope your scripts can be integrated to the task plugin soon.

**Comment by claremacrae** [comment]
@702573N Whilst this code was updating very frequently, I could not see how to integrate it in Tasks and keep up with your rate of change.

It seems to have settled down now, and I too would love to make it available in Tasks.
